// <auto-generated />
namespace todo.dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_todo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_todo));
        
        string IMigrationMetadata.Id
        {
            get { return "201406280940357_add_todo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
